mode = "replicate_deepinsight"
usepredictions = true;% predictions from deepinsight?

% Add predictions to egocentric?
% ------------------------------



% Setup for the movie/plot
% ------------------------
figstr = join(mode, animID, string(sprintf('Day %d Epoch %d',dayepoch)), " ");
fig(figstr);
% CREATE PLOT INSTRUCTIONS
% ------------------------
switch mode
case 'replicate_deepinsight'
    % Position elements
    position     = struct('type','point',...
                          'field',    'pos', 'x', 1, 'y', 2, ...
                          'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    predPosition = struct('type','point','field',    'pred_pos', 'x', 1, 'y', 2, ...
                      'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    % Speed elements
    speed = struct('type',  'magnitudeElement',...
                   'field', 'pred_pos', 'val', 1, 'maxval', [], ...
                   'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    predSpeed = struct('type','magnitudeLineElement',...
                       'field',    'pred_pos', 'val', 1, 'maxval', [], ...
                       'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    % Head direction elements
    headdir = struct('type','vector',...
                     'x_y_field', 'pos',...
                     'x', 1, 'y', 1,...
                     'theta_field', 'headdir', ...
                     'theta', 1, 'r', {{6}}, ...
                      'varargin', {{'LineWidth','2'}});
    % Head direction elements
    predHeaddir = struct('type','vector',...
                     'x_y_field', 'pos',...
                     'x', 1, 'y', 1,...
                     'theta_field', 'pred_headdir', ...
                     'theta', 1, 'r', {{6}}, ...
                      'varargin', {{'LineWidth','2'}});
    % Create instructions
    instructions = [position; predPosition; speed; predSpeed; headdir; predHeaddir];
case 'current_goal'
    % Position elements
    position     = struct('type','point',...
                          'field',    'pos', 'x', 1, 'y', 2, ...
                          'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    % Speed elements
    speed = struct('type',  'magnitudeElement',...
                   'x_y_field', 'pos',...
                   'x', 1, 'y', 2, ...
                   'u_v_field', 'velocity',...
                   'u', 1, 'v', 2, ...
                   'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    predSpeed = struct('type','magnitudeLineElement',...
                       'field',    'pred_pos', 'val', 1, 'maxval', [], ...
                       'varargin', {{'LineWidth','1', 'LineStype',':', 'Marker','o'}});
    % Head direction elements
    headdir = struct('type','vector',...
                     'x_y_field', 'pos',...
                     'x', 1, 'y', 1,...
                     'theta_field', 'headdir', ...
                     'theta', 1, 'r', {{6}}, ...
                      'varargin', {{'LineWidth','2'}});
    % Head direction elements
    predHeaddir = struct('type','vector',...
                     'x_y_field', 'pos',...
                     'x', 1, 'y', 1,...
                     'theta_field', 'pred_headdir', ...
                     'theta', 1, 'r', {{6}}, ...
                      'varargin', {{'LineWidth','2'}});
    % Create instructions
    instructions = [position; predPosition; speed; predSpeed; headdir; predHeaddir];
end


posLib.plot.behavior(animID, dayepoch, egocentricStruct);
