%% 1
%  ____                    _ _                        _    ___ 
% |  _ \  ___   ___  ___  (_) |_  __      _____  _ __| | _|__ \
% | | | |/ _ \ / _ \/ __| | | __| \ \ /\ / / _ \| '__| |/ / / /
% | |_| | (_) |  __/\__ \ | | |_   \ V  V / (_) | |  |   < |_| 
% |____/ \___/ \___||___/ |_|\__|   \_/\_/ \___/|_|  |_|\_\(_) 
%                                                              

%% VISUALIZE  BEHAVIOR!
velocity = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'velVec',...
               'u', 1, 'scale', {{1}}, ...
               'varargin',...
    {{'color','red',...
    'LineWidth',3,...
    'LineStyle',':',...
    'Marker','o',...
    'MarkerSize',4}});
% Speed elements
goalVec = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'currentGoalVec',...
               'u', 1, 'scale', {{1}}, ...
               'varargin', ...
    {{'color','blue',...
    'LineWidth',3,...
    'LineStyle',':',...
    'Marker','o',...
    'MarkerSize',4}});
headVec = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'headVec',...
               'u', 1, 'scale', {{1}}, ...
               'varargin',...
    {{'color','green',...
    'LineWidth',2,...
    'LineStyle',':',...
    'Marker','o',...
    'MarkerSize',4}});

egoVec = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'headVec',...
               'u', 1, 'scale', {{1}}, ...
               'varargin',...
    {{'color','blue',...
    'LineWidth',3,...
    'LineStyle',':',...
    'Marker','o',...
    'MarkerSize',4}});
egoVec = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'headVec',...
               'u', 1, 'scale', {{1}}, ...
               'axNum',1,...
               'varargin',...
    {{'color','green',...
    'LineWidth',3,...
    'LineStyle',':',...
    'Marker','o',...
    'MarkerSize',4}});


instructions = {goalVec, headVec};
