
%% VISUALIZE  BEHAVIOR!
velocity = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'velVec',...
               'u', 1, 'scale', {{1}}, ...
               'varargin',...
    {{'color','red',...
    'LineWidth',3,...
    'LineStyle',':',...
    'Marker','o',...
    'MarkerSize',4}});

% gaoll vector plots
goalVec = struct('type',  'vector',...
               'field1', 'pos',...
               'x', 1, 'y', 2, ...
               'field2', 'currentGoalVec',...
               'u', 1, 'scale', {{1}}, ...
               'varargin', ...
    {{'color',    'blue', ...
    'LineWidth',  3,      ...
    'LineStyle',  ':',    ...
    'Marker',     'o',    ...
    'MarkerSize', 4}});

% Grid state position
cuemem_state = struct('type',  'positionGridState',...
               'field1', 'pos', ...
               'position', 1:2, ...
               'field2', 'predict_cuememory_Y',... TODO STOPPED HERE
               'state',  1:2,   'scale', {{1}}, ...
               'height', {{1}}, 'width', {{1}}, ...
               'varargin', ...
    {{'color',    'blue', ...
    'shape',    "rect", ...
    'LineWidth',  3,      ...
    'LineStyle',  ':',    ...
    'Marker',     'o',    ...
    'MarkerSize', 4}});

instructions = {goalVec, velocity, cuemem_state};

